// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using UIKit;

namespace Talat
{
    internal class BanksPickerModel : UIPickerViewModel
    {
        public EventHandler ValueChanged;
        public string SelectedBankByUser;
        private List<string> bankList;

        public BanksPickerModel(List<string> bankList)
        {
            this.bankList = bankList;
        }

        public override nint GetRowsInComponent(UIPickerView pickerView, nint component)
        {
            return bankList.Count;
        }

        public override nint GetComponentCount(UIPickerView pickerView)
        {
            return 1;
        }

        public override string GetTitle(UIPickerView pickerView, nint row, nint component)
        {
            return bankList[(int)row];
        }

        public override void Selected(UIPickerView pickerView, nint row, nint component)
        {
            var bank = bankList[(int)row];
            SelectedBankByUser = bank;
            ValueChanged(null, null);
        }

        //internal string SelectedBankByUser;
        //private List<string> bankList;

        //public BanksPickerModel(List<string> bankList)
        //{
        //    this.bankList = bankList;
        //}

        //public Action<object, object> ValueChanged { get; internal set; }

        //public static implicit operator UIPickerViewModel(BanksPickerModel v)
        //{
        //    throw new NotImplementedException();
        //}
    }
}