// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using UIKit;

namespace Talat
{
    internal class TMChoicePickerModel : UIPickerViewModel
    {

        public EventHandler ValueChanged;
        public string SelectedWhenToGetTippedByUser;
        private List<string> getTippedList;

        public TMChoicePickerModel(List<string> getTippedList)
        {
            this.getTippedList = getTippedList;
        }

        public override nint GetRowsInComponent(UIPickerView pickerView, nint component)
        {
            return getTippedList.Count;
        }

        public override nint GetComponentCount(UIPickerView pickerView)
        {
            return 1;
        }

        public override string GetTitle(UIPickerView pickerView, nint row, nint component)
        {
            return getTippedList[(int)row];
        }

        public override void Selected(UIPickerView pickerView, nint row, nint component)
        {
            var whenToGetTipped = getTippedList[(int)row];
            SelectedWhenToGetTippedByUser = whenToGetTipped;
            ValueChanged(null, null);
        }
    }
}