// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using Newtonsoft.Json;
using Talat.Models;
using Talat.Utils;
using UIKit;

namespace Talat
{
	public partial class DashboardScreen : UIViewController
	{
        public decimal accBalance;
        public string accName;
        public string accNumber; 


		public DashboardScreen (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            accNameLabel.Text = accName;
            accNumberLabel.Text = accNumber;
            accBalanceLabel.Text = "₦" + accBalance.ToString("N0");
        }


        public override void ViewWillAppear(bool animated)
        {
            base.ViewWillAppear(animated);

            this.NavigationController.NavigationBarHidden = true;

            getUserWalletBalance();
        }


        public DashboardScreen() : base()
        {

        }




        private async void getUserWalletBalance()
        {
            var user = MemoryManager.getUseAccountLogin("user_key");
            {
                if(user != null)
                {
                    var reult = await NetworkUtil.GetQueryAsyc("Users/UserDetails", user.acctNumber, "acctNum");
                    if (!string.IsNullOrEmpty(reult))
                    {
                        var result = JsonConvert.DeserializeObject<LoginResponse>(reult);
                        if (result != null)
                        {
                            accBalanceLabel.Text = "₦" + result.acctBalance.ToString("N0");
                            MemoryManager.setUserAccountLog(result,"user_key");
                        }

                    }
                }
            }
            
        }

    }
}
