// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Talat
{
	public partial class PasswordField : UITextField
	{
		public PasswordField (IntPtr handle) : base (handle)
		{
		}
	}
}
