// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Talat
{
	public partial class SignupSuccessScreen : UIViewController
	{

		public string newEmail;

		public SignupSuccessScreen (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            gotoLogin.TouchUpInside += GotoLogin_TouchUpInside;
        }

        private void GotoLogin_TouchUpInside(object sender, EventArgs e)
        {
			PerformSegue("toLogin", null);
        }

        public override void PrepareForSegue(UIStoryboardSegue segue, NSObject sender)
        {
            base.PrepareForSegue(segue, sender);

            if (segue.Identifier == "toLogin")
            {
                var loginScreen = segue.DestinationViewController as LoginScreen;
                loginScreen.newEmail = newEmail;
            }
        }

        public override void ViewWillAppear(bool animated)
		{
			base.ViewWillAppear(animated);

			this.NavigationController.NavigationBarHidden = true;
		}
	}
}
