// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using Talat.Models;
using Talat.Utils;
using UIKit;

namespace Talat
{
	public partial class ToTransferSuccess : UIViewController
	{

		public decimal amountToSend;
		public string recipientLabel;

		public decimal walletBalance;
		public string tipPercent;

		public SendMoneyResponse sendMoneyResponse;
		public WalletDetailsResponse walletDetailsResponse;
		public string message;


		public ToTransferSuccess(IntPtr handle) : base(handle)
		{

		}


		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			NavigationItem.HidesBackButton = true;

			transferSuccessToDashboard.TouchUpInside += TransferSuccessToDashboard_TouchUpInside;

			transferSuccessAmount.Text = "₦" + amountToSend;
			transferSuccessAccName.Text = recipientLabel;

			transferSuccessTipAmount.Text = "₦" + walletBalance;
			transferSuccessTipPercent.Text = tipPercent + "%";
			toSuccessRestView.Hidden = true;
			var isTipStatus = MemoryManager.getSuccessScreenTipStatus("tip_key");
			if(isTipStatus != null && isTipStatus.status)
            {
				toSuccessRestView.Hidden = false;
				transferSuccessTipPercent.Text = isTipStatus.percent + "%";
				transferSuccessTipAmount.Text = "₦" + sendMoneyResponse.tipAmount.ToString("N0");
            }
		}

        private void TransferSuccessToDashboard_TouchUpInside(object sender, EventArgs e)
        {
			foreach (var vc in NavigationController.ViewControllers)
			{
				if(vc is DashboardScreen)
                {
					NavigationController?.PopToViewController(vc, animated: true);

				}
			}

		}
	}
}
