// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Talat
{
	public partial class CustomTransactionCell : UITableViewCell
	{

		public CustomTransactionCell()
        {

        }
		public CustomTransactionCell (IntPtr handle) : base (handle)
		{

		}

		public void PopulateCell(decimal amount, string recipientAccount, string senderAccount, string date, string refID)
        {
			amountLabel.Text = "₦" + amount.ToString("N0");
			recipientLabel.Text = recipientAccount;
			senderLabel.Text = senderAccount;
			dateLabel.Text = DateTime.Parse(date).ToString("MM/dd/yyyy hh:mm tt");
			referenceLabel.Text = refID;
        }

		

	}
}
