// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Talat
{
	public partial class CustomTipTransactionCell : UITableViewCell
	{

		public CustomTipTransactionCell()
		{

		}
		public CustomTipTransactionCell (IntPtr handle) : base (handle)
		{
		}

        public void PopulateCell(decimal amount, decimal tipAmount, string tipPercent, string date)
        {
			tippedTransAmount.Text = "₦" + amount.ToString("N0");
			tippedAmount.Text = "₦" + tipAmount.ToString("N0");
            tippedPercent.Text = tipPercent + "%";
			tippedDate.Text = DateTime.Parse(date).ToString("MM/dd/yyyy hh:mm tt");
		}
    }
}
