// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Talat
{
	public partial class ScrollViewPage : UIViewController
	{
		public ScrollViewPage (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            myScroll.ContentSize = myView.Frame.Size;
            myScroll.Scrolled += (sender, e) => {
                myPager.CurrentPage = (nint)(myScroll.ContentOffset.X / myScroll.Frame.Width);
            };



            secondScroll.ShowsHorizontalScrollIndicator = false;
            secondScroll.ContentSize = secondView.Frame.Size;
            secondScroll.Scrolled += (sender, e) => {
                secondPager.CurrentPage = (nint)(secondScroll.ContentOffset.X / secondScroll.Frame.Width);
            };
            // Perform any additional setup after loading the view, typically from a nib.  
        }
    }
}
