// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Talat
{
	public partial class Test1 : UIViewController
	{
		public Test1 (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            MyScrollView.ContentSize = MyView.Frame.Size;
            MyScrollView.Scrolled += (sender, e) => {
                MyPager.CurrentPage = (nint)(MyScrollView.ContentOffset.X / MyScrollView.Frame.Width);
            };
            // Perform any additional setup after loading the view, typically from a nib.  
        }
    }
}
